/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define CONE_BIG_MASK_ANIM "ship.umgah.graphics.cone.large"
#define CONE_MED_MASK_ANIM "ship.umgah.graphics.cone.medium"
#define CONE_SML_MASK_ANIM "ship.umgah.graphics.cone.small"
#define SPRITZ_MASK_PMAP_ANIM "ship.umgah.graphics.spritz"
#define UMGAH_BIG_MASK_PMAP_ANIM "ship.umgah.graphics.drone.large"
#define UMGAH_CAPTAIN_MASK_PMAP_ANIM "ship.umgah.graphics.captain"
#define UMGAH_ICON_MASK_PMAP_ANIM "ship.umgah.icons"
#define UMGAH_MED_MASK_PMAP_ANIM "ship.umgah.graphics.drone.medium"
#define UMGAH_MICON_MASK_PMAP_ANIM "ship.umgah.meleeicons"
#define UMGAH_RACE_STRINGS "ship.umgah.text"
#define UMGAH_SHIP_SOUNDS "ship.umgah.sounds"
#define UMGAH_SML_MASK_PMAP_ANIM "ship.umgah.graphics.drone.small"
#define UMGAH_VICTORY_SONG "ship.umgah.ditty"
