/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define LIMPETS_BIG_MASK_PMAP_ANIM "ship.vux.graphics.limpets.large"
#define LIMPETS_MED_MASK_PMAP_ANIM "ship.vux.graphics.limpets.medium"
#define LIMPETS_SML_MASK_PMAP_ANIM "ship.vux.graphics.limpets.small"
#define SLIME_MASK_PMAP_ANIM "ship.vux.graphics.slime"
#define VUX_BIG_MASK_PMAP_ANIM "ship.vux.graphics.intruder.large"
#define VUX_CAPTAIN_MASK_PMAP_ANIM "ship.vux.graphics.captain"
#define VUX_ICON_MASK_PMAP_ANIM "ship.vux.icons"
#define VUX_MED_MASK_PMAP_ANIM "ship.vux.graphics.intruder.medium"
#define VUX_MICON_MASK_PMAP_ANIM "ship.vux.meleeicons"
#define VUX_RACE_STRINGS "ship.vux.text"
#define VUX_SHIP_SOUNDS "ship.vux.sounds"
#define VUX_SML_MASK_PMAP_ANIM "ship.vux.graphics.intruder.small"
#define VUX_VICTORY_SONG "ship.vux.ditty"
