/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define HORN_BIG_MASK_PMAP_ANIM "ship.thraddash.graphics.horn.large"
#define HORN_MED_MASK_PMAP_ANIM "ship.thraddash.graphics.horn.medium"
#define HORN_SML_MASK_PMAP_ANIM "ship.thraddash.graphics.horn.small"
#define NAPALM_BIG_MASK_PMAP_ANIM "ship.thraddash.graphics.napalm.large"
#define NAPALM_MED_MASK_PMAP_ANIM "ship.thraddash.graphics.napalm.medium"
#define NAPALM_SML_MASK_PMAP_ANIM "ship.thraddash.graphics.napalm.small"
#define THRADDASH_BIG_MASK_PMAP_ANIM "ship.thraddash.graphics.torch.large"
#define THRADDASH_CAPTAIN_MASK_PMAP_ANIM "ship.thraddash.graphics.captain"
#define THRADDASH_ICON_MASK_PMAP_ANIM "ship.thraddash.icons"
#define THRADDASH_MED_MASK_PMAP_ANIM "ship.thraddash.graphics.torch.medium"
#define THRADDASH_MICON_MASK_PMAP_ANIM "ship.thraddash.meleeicons"
#define THRADDASH_RACE_STRINGS "ship.thraddash.text"
#define THRADDASH_SHIP_SOUNDS "ship.thraddash.sounds"
#define THRADDASH_SML_MASK_PMAP_ANIM "ship.thraddash.graphics.torch.small"
#define THRADDASH_VICTORY_SONG "ship.thraddash.ditty"
