/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define HUMAN_BIG_MASK_PMAP_ANIM "ship.earthling.graphics.human.large"
#define HUMAN_CAPTAIN_MASK_PMAP_ANIM "ship.earthling.graphics.captain"
#define HUMAN_ICON_MASK_PMAP_ANIM "ship.earthling.icons"
#define HUMAN_MED_MASK_PMAP_ANIM "ship.earthling.graphics.human.medium"
#define HUMAN_MICON_MASK_PMAP_ANIM "ship.earthling.meleeicons"
#define HUMAN_RACE_STRINGS "ship.earthling.text"
#define HUMAN_SHIP_SOUNDS "ship.earthling.sounds"
#define HUMAN_SML_MASK_PMAP_ANIM "ship.earthling.graphics.human.small"
#define HUMAN_VICTORY_SONG "ship.earthling.ditty"
#define SATURN_BIG_MASK_PMAP_ANIM "ship.earthling.graphics.saturn.large"
#define SATURN_MED_MASK_PMAP_ANIM "ship.earthling.graphics.saturn.medium"
#define SATURN_SML_MASK_PMAP_ANIM "ship.earthling.graphics.saturn.small"
