/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define COMMANDER_COLOR_MAP "comm.commander.colortable"
#define COMMANDER_CONVERSATION_PHRASES "comm.commander.dialogue"
#define COMMANDER_FONT "comm.commander.font"
#define COMMANDER_LOWPOW_MUSIC "comm.commander.lowpower.music"
#define COMMANDER_MUSIC "comm.commander.music"
#define COMMANDER_PMAP_ANIM "comm.commander.graphics"
#define COMMANDER_SCRIPT "comm.commander.script"
#define STARBASE_ALT_MUSIC "comm.starbase.music"
#define STARBASE_CONVERSATION_PHRASES "comm.starbase.dialogue"
#define STARBASE_SCRIPT "comm.starbase.script"
