/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define MELNORME_COLOR_MAP "comm.melnorme.colortable"
#define MELNORME_CONVERSATION_PHRASES "comm.melnorme.dialogue"
#define MELNORME_FONT "comm.melnorme.font"
#define MELNORME_MUSIC "comm.melnorme.music"
#define MELNORME_PMAP_ANIM "comm.melnorme.graphics"
#define MELNORME_SCRIPT "comm.melnorme.script"
