/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define CHMMR_BIG_MASK_PMAP_ANIM "ship.chmmr.graphics.avatar.large"
#define CHMMR_CAPTAIN_MASK_PMAP_ANIM "ship.chmmr.graphics.captain"
#define CHMMR_ICON_MASK_PMAP_ANIM "ship.chmmr.icons"
#define CHMMR_MED_MASK_PMAP_ANIM "ship.chmmr.graphics.avatar.medium"
#define CHMMR_MICON_MASK_PMAP_ANIM "ship.chmmr.meleeicons"
#define CHMMR_RACE_STRINGS "ship.chmmr.text"
#define CHMMR_SHIP_SOUNDS "ship.chmmr.sounds"
#define CHMMR_SML_MASK_PMAP_ANIM "ship.chmmr.graphics.avatar.small"
#define CHMMR_VICTORY_SONG "ship.chmmr.ditty"
#define MUZZLE_BIG_MASK_PMAP_ANIM "ship.chmmr.graphics.muzzle.large"
#define MUZZLE_MED_MASK_PMAP_ANIM "ship.chmmr.graphics.muzzle.medium"
#define MUZZLE_SML_MASK_PMAP_ANIM "ship.chmmr.graphics.muzzle.small"
#define SATELLITE_BIG_MASK_PMAP_ANIM "ship.chmmr.graphics.satellite.large"
#define SATELLITE_MED_MASK_PMAP_ANIM "ship.chmmr.graphics.satellite.medium"
#define SATELLITE_SML_MASK_PMAP_ANIM "ship.chmmr.graphics.satellite.small"
