/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UTWIG_COLOR_MAP "comm.utwig.colortable"
#define UTWIG_CONVERSATION_PHRASES "comm.utwig.dialogue"
#define UTWIG_FONT "comm.utwig.font"
#define UTWIG_MUSIC "comm.utwig.music"
#define UTWIG_PMAP_ANIM "comm.utwig.graphics"
#define UTWIG_SCRIPT "comm.utwig.script"
#define UTWIG_ULTRON_MUSIC "comm.utwig.ultron.music"
