/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define URQUAN_DRONE_MICON_MASK_PMAP_ANIM "ship.drone.meleeicons"
