function(quieter_check_symbol symbol header result_var)
    set(CMAKE_REQUIRED_QUIET TRUE)  # Suppress all check output
    check_symbol_exists(${symbol} "${header}" ${result_var})
    if(${result_var})
        message(STATUS "Symbol '${symbol}' found")
    else()
        message(STATUS "Symbol '${symbol}' not found")
    endif()
endfunction()

function(check_type type result_var)
    set(CMAKE_REQUIRED_QUIET TRUE)
    check_type_size(${type} ${result_var})
    if(${result_var})
        message(STATUS "Type '${type}' found")
    else()
        message(STATUS "Type '${type}' not found")
    endif()
endfunction()

function(check_include header result_var)
    set(CMAKE_REQUIRED_QUIET TRUE)
    check_include_file(${header} ${result_var})
    if(${result_var})
        message(STATUS "Header '${header}' found")
    else()
        message(STATUS "Header '${header}' not found")
    endif()
endfunction()

function(set_if condition var value)
    if(${condition})
        set(${var} "${value}" PARENT_SCOPE)
    endif()
endfunction()

function(set_if_else condition var var_1 var_2)
    if(${condition})
        set(${var} "${var_1}" PARENT_SCOPE)
    else()
        set(${var} "${var_2}" PARENT_SCOPE)
    endif()
endfunction()

function(set_makeinfo_env env_var cmake_var)
    if(${cmake_var})
        set(ENV{${env_var}} "1")
    else()
        set(ENV{${env_var}} "0")
    endif()
endfunction()

function(set_env_if env_var value condition)
    if(${condition})
        set(ENV{${env_var}} "${value}")
    endif()
endfunction()

function(set_config_define var)
    if(${var})
        set(${var} "#define ${var}" PARENT_SCOPE)
    else()
        set(${var} "#undef ${var}" PARENT_SCOPE)
    endif()
endfunction()

macro(append_list list libraries condition)
    if(${condition})
        list(APPEND ${list} ${libraries})
    endif()
endmacro()