/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define GENERATOR_BIG_MASK_ANIM "ship.samatra.graphics.generator.large"
#define GENERATOR_MED_MASK_PMAP_ANIM "ship.samatra.graphics.generator.medium"
#define GENERATOR_SML_MASK_PMAP_ANIM "ship.samatra.graphics.generator.small"
#define SAMATRA_BIG_MASK_ANIM "ship.samatra.graphics.samatra.large"
#define SAMATRA_CAPTAIN_MASK_PMAP_ANIM "ship.samatra.graphics.captain"
#define SAMATRA_MED_MASK_PMAP_ANIM "ship.samatra.graphics.samatra.medium"
#define SAMATRA_SHIP_SOUNDS "ship.samatra.sounds"
#define SAMATRA_SML_MASK_PMAP_ANIM "ship.samatra.graphics.samatra.small"
#define SAMATRA_VICTORY_SONG "ship.samatra.ditty"
#define SENTINEL_BIG_MASK_ANIM "ship.samatra.graphics.sentinel.large"
#define SENTINEL_MED_MASK_PMAP_ANIM "ship.samatra.graphics.sentinel.medium"
#define SENTINEL_SML_MASK_PMAP_ANIM "ship.samatra.graphics.sentinel.small"
