/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SLYLANDRO_COLOR_MAP "comm.slylandro.colortable"
#define SLYLANDRO_CONVERSATION_PHRASES "comm.slylandro.dialogue"
#define SLYLANDRO_FONT "comm.slylandro.font"
#define SLYLANDRO_MUSIC "comm.slylandro.music"
#define SLYLANDRO_PMAP_ANIM "comm.slylandro.graphics"
#define SLYLANDRO_SCRIPT "comm.slylandro.script"
