/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define MYCON_COLOR_MAP "comm.mycon.colortable"
#define MYCON_CONVERSATION_PHRASES "comm.mycon.dialogue"
#define MYCON_FONT "comm.mycon.font"
#define MYCON_MUSIC "comm.mycon.music"
#define MYCON_PMAP_ANIM "comm.mycon.graphics"
#define MYCON_SCRIPT "comm.mycon.script"
