/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define THRADD_COLOR_MAP "comm.thraddash.colortable"
#define THRADD_CONVERSATION_PHRASES "comm.thraddash.dialogue"
#define THRADD_FONT "comm.thraddash.font"
#define THRADD_MUSIC "comm.thraddash.music"
#define THRADD_PMAP_ANIM "comm.thraddash.graphics"
#define THRADD_SCRIPT "comm.thraddash.script"
