/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define REBEL_CONVERSATION_PHRASES "comm.yehat.rebel.dialogue"
#define REBEL_MUSIC "comm.yehat.rebel.music"
#define YEHAT_COLOR_MAP "comm.yehat.colortable"
#define YEHAT_CONVERSATION_PHRASES "comm.yehat.dialogue"
#define YEHAT_FONT "comm.yehat.font"
#define YEHAT_MUSIC "comm.yehat.music"
#define YEHAT_PMAP_ANIM "comm.yehat.graphics"
#define YEHAT_SCRIPT "comm.yehat.script"
