#ifndef GENDEF_H
#define GENDEF_H

// JSD planets/generate.h no longer needed once GenerateFunctions is moved there.  It's where it belongs
// and the include of generate.h is causing circular definitions elsewhere.
// Added ARILOU_DEFINED = 0 (for location of quasi-portal and arilou zone of influence).
// Split RAINBOW_DEFINED into separate entries (like MELNORME0_DEFINED is) so they can be scattered.
// Added NUM_PLOTS for plot iteration.
// These are used in the plot randomizer.
//#include "planets/generate.h"
#include "libs/compiler.h"

#if defined(__cplusplus)
extern "C" {
#endif

//const GenerateFunctions *getGenerateFunctions (BYTE Index);

enum
{
	ARILOU_DEFINED = 0,
	SOL_DEFINED = 1,
	SHOFIXTI_DEFINED,
	MAIDENS_DEFINED,
	START_COLONY_DEFINED,
	SPATHI_DEFINED,
	ZOQFOT_DEFINED,

	MELNORME0_DEFINED,
	MELNORME1_DEFINED,
	MELNORME2_DEFINED,
	MELNORME3_DEFINED,
	MELNORME4_DEFINED,
	MELNORME5_DEFINED,
	MELNORME6_DEFINED,
	MELNORME7_DEFINED,
	MELNORME8_DEFINED,

	TALKING_PET_DEFINED,
	CHMMR_DEFINED,
	SYREEN_DEFINED,
	BURVIXESE_DEFINED,
	SLYLANDRO_DEFINED,
	DRUUGE_DEFINED,
	BOMB_DEFINED,
	AQUA_HELIX_DEFINED,
	SUN_DEVICE_DEFINED,
	TAALO_PROTECTOR_DEFINED,
	SHIP_VAULT_DEFINED,
	URQUAN_WRECK_DEFINED,
	VUX_BEAST_DEFINED,
	SAMATRA_DEFINED,
	ZOQ_SCOUT_DEFINED,
	MYCON_DEFINED,
	EGG_CASE0_DEFINED,
	EGG_CASE1_DEFINED,
	EGG_CASE2_DEFINED,
	PKUNK_DEFINED,
	UTWIG_DEFINED,
	SUPOX_DEFINED,
	YEHAT_DEFINED,
	VUX_DEFINED,
	ORZ_DEFINED,
	THRADD_DEFINED,
	RAINBOW0_DEFINED,
	RAINBOW1_DEFINED,
	RAINBOW2_DEFINED,
	RAINBOW3_DEFINED,
	RAINBOW4_DEFINED,
	RAINBOW5_DEFINED,
	RAINBOW6_DEFINED,
	RAINBOW7_DEFINED,
	RAINBOW8_DEFINED,
	RAINBOW9_DEFINED,
	ILWRATH_DEFINED,
	ANDROSYNTH_DEFINED,
	MYCON_TRAP_DEFINED,
	URQUAN_DEFINED,
	KOHRAH_DEFINED,
	DESTROYED_STARBASE_DEFINED,
	MOTHER_ARK_DEFINED,
	ZOQ_COLONY0_DEFINED,
	ZOQ_COLONY1_DEFINED,
	ALGOLITES_DEFINED,
	SPATHI_MONUMENT_DEFINED,
	EXCAVATION_SITE_DEFINED,
	NUM_PLOTS	// Must be last entry, any new entries should have plot min/max added in gendef.c
};

#define UMGAH_DEFINED TALKING_PET_DEFINED

#if defined(__cplusplus)
}
#endif

#endif  /* GENDEF_H */

