/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define LANDER_FONT "font.lander"
#define MICRO_FONT "font.micro"
#define MICRO_THIN_FONT "font.micro.thin"
#define PLAYER_FONT "font.player"
#define PT13AA_FONT "credits.font.pt13"
#define PT17AA_FONT "credits.font.pt17"
#define PT45AA_FONT "credits.font.pt45"
#define STARCON_FONT "font.starcon"
#define TINY_FONT "font.tiny"
#define TINY_FONT_BOLD "font.tiny.bold"
#define TINY_FONT_COND "font.tiny.condensed"
#define COMPUTER_FONT "comm.computer.font"
#define LABEL_FONT "font.label"
#define SQUARE_FONT "font.square"
#define SLAB_FONT "font.slab"
#define MELEE_TITLE_FONT "font.melee.title"
#define BUTTON_FONT "font.button"