/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define LANDER_FONT "font.lander"
#define MICRO_FONT "font.micro"
#define PLAYER_FONT "font.player"
#define PT13AA_FONT "credits.font.pt13"
#define PT17AA_FONT "credits.font.pt17"
#define PT45AA_FONT "credits.font.pt45"
#define STARCON_FONT "font.starcon"
#define TINY_FONT "font.tiny"
#define TINY_FONT_FB "font.tiny.fb"
#define TINY_FONT_HD "font.tiny.hd"
#define TINY_FONT_SS "font.tiny.ss"
#define PLAYER_FONT_FB "font.player.fb"
#define PLAYER_FONT_HD "font.player.hd"
#define STARCON_FONT_FB "font.starcon.fb"
#define STARCON_FONT_HD "font.starcon.hd"
#define COMPUTER_FONT "comm.computer.font"