/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define EVENT_SCRIPT "event.script"
#define SCRIPT_DIR_INITGAME "script.dir.initgame"
