/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define GAME_SOUNDS "sounds.battle"
#define LANDER_SOUNDS "sounds.lander"
#define MENU_SOUNDS "sounds.menu"
