/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef UQM_JOURNAL_H
#define UQM_JOURNAL_H

enum
{
	NO_JOURNAL_ENTRY,
	OPEN_OBJECTIVE,
	CLOSED_OBJECTIVE,

	PRESS_LEFT_RIGHT,

	CAPTAINS_LOG,
	OBJECTIVES_JOURNAL_HEADER,
	ALIENS_JOURNAL_HEADER,
	ARTIFACTS_JOURNAL_HEADER,

	VISIT_EARTH,
	CONTACT_EARTH,
	GET_RADIOACTIVES,
	GIVE_RADIOACTIVES,
	NEED_LANDER,
	NEED_LANDER_AGAIN,
	NEED_FUEL,
	NEED_FUEL_AGAIN,
	DESTROY_MOONBASE,
	REPORT_MOONBASE,
	RECRUIT_EARTH,

	FIND_FWIFFO,
	RECRUIT_FWIFFO,
	MET_FWIFFO,

	INVESTIGATE_RIGEL,

	CONTACT_ARILOU,
	CONTACT_CHENJESU,
	CONTACT_MMRNMHRM,
	CONTACT_MELNORME,
	MET_THE_MELNORME,
	CONTACT_ANDROSYNTH,
	VISIT_ORZ_HOMEWORLD,
	ALLY_ORZ,

	HAYES_PKUNK,
	HEARD_OF_PKUNK_ILWRATH,
	HEARD_OF_PKUNK_MELNORME,
	GO_TO_PKUNK_HOMEWORLD,
	MET_THE_PKUNK,

	CONTACT_SHOFIXTI,
	RECRUIT_THE_SHOFIXTI,
	SENT_SHOFIXTI,
	SHOFIXTI_REPOPULATED,

	CONTACT_SPATHI,

	CONTACT_SUPOX,
	MET_THE_SUPOX,

	CONTACT_SYREEN,
	CONTACT_SYREEN_HW,
	MET_THE_SYREEN,

	HAYES_THRADDASH,
	GENERAL_THRADDASH,
	MELNORME_THRADDASH,
	CONTACTED_THRADDASH,

	INVESTIGATE_UTWIG,
	CONTACTED_UTWIG,

	CONTACT_UMGAH,
	MET_THE_UMGAH,

	CONTACT_YEHAT,
	MELNORME_YEHAT,
	MET_THE_YEHAT,

	HAYES_ZFP,
	CONTACT_ZOQFOTPIK,

	INV_SLYLANDRO_PROBE,
	INV_SLYLANDRO_ZFP,
	INV_SLY_THRADD_00,
	INV_SLY_THRADD_01,
	MELNORME_SLYLANDRO,
	SLY_PROBE_FAULTY,
	SLYLANDRO_CONVINCED,

	FIND_PORTAL_TIME,
	FIND_PORTAL,
	ASK_UMGAH_TPET,
	REPORT_UMGAH_WEIRD,
	FOLLOWUP_UMGAH_WEIRD,
	CHECK_UMGAH_HOME,
	FIND_SHIELD,
	FACE_DNYARRI,
	GET_DNYARRI,

	GET_AQUAHELIX,
	LEARN_AQUAHELIX,
	USE_AQUAHELIX,

	GET_CLEARSPINDLE,
	LEARN_CLEARSPINDLE,
	USE_CLEARSPINDLE,

	GET_EGGCASE,

	GET_ROSYSPHERE,
	LEARN_ROSYSPHERE,
	USE_ROSYSPHERE,

	GET_MAIDENS,

	CHECK_PLAYGROUND,
	GET_MINDSHIELD,

	CHECK_CRASH_SITE,
	GET_WARPPOD,
	LEARN_WARPPOD,
	GIVE_WARPPOD,

	GET_SPAWNER,

	GET_BOMB,
	IMPROVE_BOMB,

	FIND_RAINBOW_SEXTANTIS,
	FIND_RAINBOW_LEPORIS,

	FOUND_RAINBOW_0,
	FOUND_RAINBOW_1,
	FOUND_RAINBOW_2,
	FOUND_RAINBOW_3,
	FOUND_RAINBOW_4,
	FOUND_RAINBOW_5,
	FOUND_RAINBOW_6,
	FOUND_RAINBOW_7,
	FOUND_RAINBOW_8,
	FOUND_RAINBOW_9,

	FIND_DEFEAT_URQUAN,
	FIND_DESTROY_SAMATRA,
	FIND_ACCESS_SAMATRA,
	DESTROY_SAMATRA,

	NUM_JOURNAL_STRINGS
};

extern BOOLEAN Journal (void);

extern BOOLEAN FwiffoCanJoin;

#endif /* UQM_JOURNAL_H */
