/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define CHMMR_COLOR_MAP "comm.chmmr.colortable"
#define CHMMR_CONVERSATION_PHRASES "comm.chmmr.dialogue"
#define CHMMR_FONT "comm.chmmr.font"
#define CHMMR_MUSIC "comm.chmmr.music"
#define CHMMR_PROCESS_MUSIC "comm.chmmr.process.music"
#define CHMMR_PMAP_ANIM "comm.chmmr.graphics"
#define CHMMR_RED_PMAP_ANIM "comm.chmmr.red.graphics"
#define CHMMR_SCRIPT "comm.chmmr.script"
