/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define PKUNK_COLOR_MAP "comm.pkunk.colortable"
#define PKUNK_CONVERSATION_PHRASES "comm.pkunk.dialogue"
#define PKUNK_FONT "comm.pkunk.font"
#define PKUNK_MUSIC "comm.pkunk.music"
#define PKUNK_PMAP_ANIM "comm.pkunk.graphics"
#define PKUNK_SCRIPT "comm.pkunk.script"
