/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define DISCRIM_BIG_MASK_PMAP_ANIM "ship.spathi.graphics.butt.large"
#define DISCRIM_MED_MASK_PMAP_ANIM "ship.spathi.graphics.butt.medium"
#define DISCRIM_SML_MASK_PMAP_ANIM "ship.spathi.graphics.butt.small"
#define MISSILE_BIG_MASK_PMAP_ANIM "ship.spathi.graphics.missile.large"
#define MISSILE_MED_MASK_PMAP_ANIM "ship.spathi.graphics.missile.medium"
#define MISSILE_SML_MASK_PMAP_ANIM "ship.spathi.graphics.missile.small"
#define SPATHI_BIG_MASK_PMAP_ANIM "ship.spathi.graphics.eluder.large"
#define SPATHI_CAPTAIN_MASK_PMAP_ANIM "ship.spathi.graphics.captain"
#define SPATHI_ICON_MASK_PMAP_ANIM "ship.spathi.icons"
#define SPATHI_MED_MASK_PMAP_ANIM "ship.spathi.graphics.eluder.medium"
#define SPATHI_MICON_MASK_PMAP_ANIM "ship.spathi.meleeicons"
#define SPATHI_RACE_STRINGS "ship.spathi.text"
#define SPATHI_SHIP_SOUNDS "ship.spathi.sounds"
#define SPATHI_SML_MASK_PMAP_ANIM "ship.spathi.graphics.eluder.small"
#define SPATHI_VICTORY_SONG "ship.spathi.ditty"
