/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ILWRATH_COLOR_MAP "comm.ilwrath.colortable"
#define ILWRATH_CONVERSATION_PHRASES "comm.ilwrath.dialogue"
#define ILWRATH_FONT "comm.ilwrath.font"
#define ILWRATH_MUSIC "comm.ilwrath.music"
#define ILWRATH_PMAP_ANIM "comm.ilwrath.graphics"
#define ILWRATH_SCRIPT "comm.ilwrath.script"
