/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define FWIFFO_MUSIC "comm.fwiffo.music"
#define SPAHOME_MUSIC "comm.safeones.music"
#define SPATHI_COLOR_MAP "comm.spathi.colortable"
#define SPATHI_CONVERSATION_PHRASES "comm.spathi.dialogue"
#define SPATHI_FONT "comm.spathi.font"
#define SPATHI_HOME_COLOR_MAP "comm.safeones.colortable"
#define SPATHI_HOME_CONVERSATION_PHRASES "comm.safeones.dialogue"
#define SPATHI_HOME_PMAP_ANIM "comm.safeones.graphics"
#define SPATHI_MUSIC "comm.spathi.music"
#define SPATHI_PMAP_ANIM "comm.spathi.graphics"
#define SPATHI_SCRIPT "comm.spathi.script"
