/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define DART_BIG_MASK_PMAP_ANIM "ship.shofixti.graphics.missile.large"
#define DART_MED_MASK_PMAP_ANIM "ship.shofixti.graphics.missile.medium"
#define DART_SML_MASK_PMAP_ANIM "ship.shofixti.graphics.missile.small"
#define DESTRUCT_BIG_MASK_ANIM "ship.shofixti.graphics.destruct.large"
#define DESTRUCT_MED_MASK_ANIM "ship.shofixti.graphics.destruct.medium"
#define DESTRUCT_SML_MASK_ANIM "ship.shofixti.graphics.destruct.small"
#define OLDSHOF_BIG_MASK_PMAP_ANIM "ship.shofixti.graphics.oldscout.large"
#define OLDSHOF_CAPTAIN_MASK_PMAP_ANIM "ship.shofixti.graphics.oldcaptain"
#define OLDSHOF_ICON_MASK_PMAP_ANIM "ship.shofixti.oldicons"
#define OLDSHOF_MED_MASK_PMAP_ANIM "ship.shofixti.graphics.oldscout.medium"
#define OLDSHOF_SML_MASK_PMAP_ANIM "ship.shofixti.graphics.oldscout.small"
#define SHOFIXTI_BIG_MASK_PMAP_ANIM "ship.shofixti.graphics.scout.large"
#define SHOFIXTI_CAPTAIN_MASK_PMAP_ANIM "ship.shofixti.graphics.captain"
#define SHOFIXTI_ICON_MASK_PMAP_ANIM "ship.shofixti.icons"
#define SHOFIXTI_MED_MASK_PMAP_ANIM "ship.shofixti.graphics.scout.medium"
#define SHOFIXTI_MICON_MASK_PMAP_ANIM "ship.shofixti.meleeicons"
#define SHOFIXTI_RACE_STRINGS "ship.shofixti.text"
#define SHOFIXTI_SHIP_SOUNDS "ship.shofixti.sounds"
#define SHOFIXTI_SML_MASK_PMAP_ANIM "ship.shofixti.graphics.scout.small"
#define SHOFIXTI_VICTORY_SONG "ship.shofixti.ditty"
