/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define GOB_BIG_MASK_PMAP_ANIM "ship.supox.graphics.glob.large"
#define GOB_MED_MASK_PMAP_ANIM "ship.supox.graphics.glob.medium"
#define GOB_SML_MASK_PMAP_ANIM "ship.supox.graphics.glob.small"
#define SUPOX_BIG_MASK_PMAP_ANIM "ship.supox.graphics.blade.large"
#define SUPOX_CAPTAIN_MASK_PMAP_ANIM "ship.supox.graphics.captain"
#define SUPOX_ICON_MASK_PMAP_ANIM "ship.supox.icons"
#define SUPOX_MED_MASK_PMAP_ANIM "ship.supox.graphics.blade.medium"
#define SUPOX_MICON_MASK_PMAP_ANIM "ship.supox.meleeicons"
#define SUPOX_RACE_STRINGS "ship.supox.text"
#define SUPOX_SHIP_SOUNDS "ship.supox.sounds"
#define SUPOX_SML_MASK_PMAP_ANIM "ship.supox.graphics.blade.small"
#define SUPOX_VICTORY_SONG "ship.supox.ditty"
