/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ARILOU_COLOR_MAP "comm.arilou.colortable"
#define ARILOU_CONVERSATION_PHRASES "comm.arilou.dialogue"
#define ARILOU_FONT "comm.arilou.font"
#define ARILOU_MUSIC "comm.arilou.music"
#define ARILOU_PMAP_ANIM "comm.arilou.graphics"
#define ARILOU_SCRIPT "comm.arilou.script"
