/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ORZ_COLOR_MAP "comm.orz.colortable"
#define ORZ_CONVERSATION_PHRASES "comm.orz.dialogue"
#define ORZ_FONT "comm.orz.font"
#define ORZ_MUSIC "comm.orz.music"
#define ORZ_PMAP_ANIM "comm.orz.graphics"
#define ORZ_ANGRY_PMAP_ANIM "comm.orz.angry.graphics"
#define ORZ_SCRIPT "comm.orz.script"
