/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define HOWITZER_BIG_MASK_PMAP_ANIM "ship.orz.graphics.howitzer.large"
#define HOWITZER_MED_MASK_PMAP_ANIM "ship.orz.graphics.howitzer.medium"
#define HOWITZER_SML_MASK_PMAP_ANIM "ship.orz.graphics.howitzer.small"
#define ORZ_BIG_MASK_PMAP_ANIM "ship.orz.graphics.nemesis.large"
#define ORZ_CAPTAIN_MASK_PMAP_ANIM "ship.orz.graphics.captain"
#define ORZ_ICON_MASK_PMAP_ANIM "ship.orz.icons"
#define ORZ_MED_MASK_PMAP_ANIM "ship.orz.graphics.nemesis.medium"
#define ORZ_MICON_MASK_PMAP_ANIM "ship.orz.meleeicons"
#define ORZ_RACE_STRINGS "ship.orz.text"
#define ORZ_SHIP_SOUNDS "ship.orz.sounds"
#define ORZ_SML_MASK_PMAP_ANIM "ship.orz.graphics.nemesis.small"
#define ORZ_VICTORY_SONG "ship.orz.ditty"
#define TURRET_BIG_MASK_PMAP_ANIM "ship.orz.graphics.turret.large"
#define TURRET_MED_MASK_PMAP_ANIM "ship.orz.graphics.turret.medium"
#define TURRET_SML_MASK_PMAP_ANIM "ship.orz.graphics.turret.small"
