/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define URQUAN_COLOR_MAP "comm.urquan.colortable"
#define URQUAN_CONVERSATION_PHRASES "comm.urquan.dialogue"
#define URQUAN_FONT "comm.urquan.font"
#define URQUAN_MUSIC "comm.urquan.music"
#define URQUAN_PROBE_MUSIC "comm.urquan.probe.music"
#define URQUAN_PMAP_ANIM "comm.urquan.graphics"
#define URQUAN_SCRIPT "comm.urquan.script"
