/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define BLASTER_BIG_MASK_PMAP_ANIM "ship.flagship.graphics.blaster.large"
#define BLASTER_MED_MASK_PMAP_ANIM "ship.flagship.graphics.blaster.medium"
#define BLASTER_SML_MASK_PMAP_ANIM "ship.flagship.graphics.blaster.small"
#define SIS_BIG_MASK_PMAP_ANIM "ship.flagship.graphics.flagship.large"
#define SIS_CAPTAIN_MASK_PMAP_ANIM "ship.flagship.graphics.captain"
#define SIS_HYPER_MASK_PMAP_ANIM "ship.flagship.graphics.hyperspace"
#define SIS_QUASI_MASK_PMAP_ANIM "ship.flagship.graphics.quasispace"
#define SIS_ICON_MASK_PMAP_ANIM "ship.flagship.icons"
#define SIS_MED_MASK_PMAP_ANIM "ship.flagship.graphics.flagship.medium"
#define SIS_SHIP_SOUNDS "ship.flagship.sounds"
#define SIS_SML_MASK_PMAP_ANIM "ship.flagship.graphics.flagship.small"
#define SIS_VICTORY_SONG "ship.flagship.ditty"
