/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SUPOX_COLOR_MAP "comm.supox.colortable"
#define SUPOX_CONVERSATION_PHRASES "comm.supox.dialogue"
#define SUPOX_FONT "comm.supox.font"
#define SUPOX_MUSIC "comm.supox.music"
#define SUPOX_PMAP_ANIM "comm.supox.graphics"
#define SUPOX_SCRIPT "comm.supox.script"
