/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define DRUUGE_COLOR_MAP "comm.druuge.colortable"
#define DRUUGE_CONVERSATION_PHRASES "comm.druuge.dialogue"
#define DRUUGE_FONT "comm.druuge.font"
#define DRUUGE_MUSIC "comm.druuge.music"
#define DRUUGE_PMAP_ANIM "comm.druuge.graphics"
#define DRUUGE_SCRIPT "comm.druuge.script"
