/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define UMGAH_COLOR_MAP "comm.umgah.colortable"
#define UMGAH_CONVERSATION_PHRASES "comm.umgah.dialogue"
#define UMGAH_FONT "comm.umgah.font"
#define UMGAH_MUSIC "comm.umgah.music"
#define UMGAH_PMAP_ANIM "comm.umgah.graphics"
#define UMGAH_SCRIPT "comm.umgah.script"
