/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SHOFIXTI_COLOR_MAP "comm.shofixti.colortable"
#define SHOFIXTI_CONVERSATION_PHRASES "comm.shofixti.dialogue"
#define SHOFIXTI_FONT "comm.shofixti.font"
#define SHOFIXTI_MUSIC "comm.shofixti.music"
#define SHOFIXTI_PMAP_ANIM "comm.shofixti.graphics"
#define SHOFIXTI_SCRIPT "comm.shofixti.script"
