/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SHIELD_BIG_MASK_ANIM "ship.yehat.graphics.shield.large"
#define SHIELD_MED_MASK_ANIM "ship.yehat.graphics.shield.medium"
#define SHIELD_SML_MASK_ANIM "ship.yehat.graphics.shield.small"
#define YEHAT_BIG_MASK_PMAP_ANIM "ship.yehat.graphics.terminator.large"
#define YEHAT_CANNON_BIG_MASK_PMAP_ANIM "ship.yehat.graphics.missile.large"
#define YEHAT_CANNON_MED_MASK_PMAP_ANIM "ship.yehat.graphics.missile.medium"
#define YEHAT_CANNON_SML_MASK_PMAP_ANIM "ship.yehat.graphics.missile.small"
#define YEHAT_CAPTAIN_MASK_PMAP_ANIM "ship.yehat.graphics.captain"
#define YEHAT_ICON_MASK_PMAP_ANIM "ship.yehat.icons"
#define YEHAT_MED_MASK_PMAP_ANIM "ship.yehat.graphics.terminator.medium"
#define YEHAT_MICON_MASK_PMAP_ANIM "ship.yehat.meleeicons"
#define YEHAT_RACE_STRINGS "ship.yehat.text"
#define YEHAT_SHIP_SOUNDS "ship.yehat.sounds"
#define YEHAT_SML_MASK_PMAP_ANIM "ship.yehat.graphics.terminator.small"
#define YEHAT_VICTORY_SONG "ship.yehat.ditty"
