/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SYREEN_COLOR_MAP "comm.syreen.colortable"
#define SYREEN_CONVERSATION_PHRASES "comm.syreen.dialogue"
#define SYREEN_FONT "comm.syreen.font"
#define SYREEN_MUSIC "comm.syreen.music"
#define SYREEN_PMAP_ANIM "comm.syreen.graphics"
#define SYREEN_SCRIPT "comm.syreen.script"
