/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define FIRE_BIG_MASK_PMAP_ANIM "ship.ilwrath.graphics.fire.large"
#define FIRE_MED_MASK_PMAP_ANIM "ship.ilwrath.graphics.fire.medium"
#define FIRE_SML_MASK_PMAP_ANIM "ship.ilwrath.graphics.fire.small"
#define ILWRATH_BIG_MASK_PMAP_ANIM "ship.ilwrath.graphics.avenger.large"
#define ILWRATH_CAPTAIN_MASK_PMAP_ANIM "ship.ilwrath.graphics.captain"
#define ILWRATH_ICON_MASK_PMAP_ANIM "ship.ilwrath.icons"
#define ILWRATH_MED_MASK_PMAP_ANIM "ship.ilwrath.graphics.avenger.medium"
#define ILWRATH_MICON_MASK_PMAP_ANIM "ship.ilwrath.meleeicons"
#define ILWRATH_RACE_STRINGS "ship.ilwrath.text"
#define ILWRATH_SHIP_SOUNDS "ship.ilwrath.sounds"
#define ILWRATH_SML_MASK_PMAP_ANIM "ship.ilwrath.graphics.avenger.small"
#define ILWRATH_VICTORY_SONG "ship.ilwrath.ditty"
