/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SLYLAND_COLOR_MAP "comm.probe.colortable"
#define SLYLAND_CONVERSATION_PHRASES "comm.probe.dialogue"
#define SLYLAND_FONT "comm.probe.font"
#define SLYLAND_MUSIC "comm.probe.music"
#define SLYLAND_PMAP_ANIM "comm.probe.graphics"
#define SLYLAND_SCRIPT "comm.probe.script"
