/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define CONFUSE_BIG_MASK_PMAP_ANIM "ship.melnorme.graphics.confuse.large"
#define CONFUSE_MED_MASK_PMAP_ANIM "ship.melnorme.graphics.confuse.medium"
#define CONFUSE_SML_MASK_PMAP_ANIM "ship.melnorme.graphics.confuse.small"
#define MELNORME_BIG_MASK_PMAP_ANIM "ship.melnorme.graphics.trader.large"
#define MELNORME_CAPTAIN_MASK_PMAP_ANIM "ship.melnorme.graphics.captain"
#define MELNORME_ICON_MASK_PMAP_ANIM "ship.melnorme.icons"
#define MELNORME_MED_MASK_PMAP_ANIM "ship.melnorme.graphics.trader.medium"
#define MELNORME_MICON_MASK_PMAP_ANIM "ship.melnorme.meleeicons"
#define MELNORME_RACE_STRINGS "ship.melnorme.text"
#define MELNORME_SHIP_SOUNDS "ship.melnorme.sounds"
#define MELNORME_SML_MASK_PMAP_ANIM "ship.melnorme.graphics.trader.small"
#define MELNORME_VICTORY_SONG "ship.melnorme.ditty"
#define PUMPUP_BIG_MASK_PMAP_ANIM "ship.melnorme.graphics.pumpup.large"
#define PUMPUP_MED_MASK_PMAP_ANIM "ship.melnorme.graphics.pumpup.medium"
#define PUMPUP_SML_MASK_PMAP_ANIM "ship.melnorme.graphics.pumpup.small"
