/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define LANCE_BIG_MASK_PMAP_ANIM "ship.utwig.graphics.lance.large"
#define LANCE_MED_MASK_PMAP_ANIM "ship.utwig.graphics.lance.medium"
#define LANCE_SML_MASK_PMAP_ANIM "ship.utwig.graphics.lance.small"
#define UTWIG_BIG_MASK_PMAP_ANIM "ship.utwig.graphics.jugger.large"
#define UTWIG_CAPTAIN_MASK_PMAP_ANIM "ship.utwig.graphics.captain"
#define UTWIG_ICON_MASK_PMAP_ANIM "ship.utwig.icons"
#define UTWIG_MED_MASK_PMAP_ANIM "ship.utwig.graphics.jugger.medium"
#define UTWIG_MICON_MASK_PMAP_ANIM "ship.utwig.meleeicons"
#define UTWIG_RACE_STRINGS "ship.utwig.text"
#define UTWIG_SHIP_SOUNDS "ship.utwig.sounds"
#define UTWIG_SML_MASK_PMAP_ANIM "ship.utwig.graphics.jugger.small"
#define UTWIG_VICTORY_SONG "ship.utwig.ditty"
