/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ZOQFOTPIK_COLOR_MAP "comm.zoqfotpik.colortable"
#define ZOQFOTPIK_CONVERSATION_PHRASES "comm.zoqfotpik.dialogue"
#define ZOQFOTPIK_FONT "comm.zoqfotpik.font"
#define ZOQFOTPIK_MUSIC "comm.zoqfotpik.music"
#define ZOQFOTPIK_PMAP_ANIM "comm.zoqfotpik.graphics"
#define ZOQFOTPIK_SCRIPT "comm.zoqfotpik.script"
